### ISSUE TITLE
Seasons/episodes to accept non-integers

### ISSUE THREAD

**Issue by staceygoers** [Podcastindex-org/podcast-namespace#108] opened 2020-11-10 22:09 UTC
We have asked Apple for this feature upgrade for a bit -- we would love to see the season/episode tags support non-integer values.

i.e. Seasons could be thematic -- the "2020 Election" or "Stories about XYZ"

I see the value more in the season tag than episode number, but why not both. :)

**Comment by daveajones** [comment] 2020-11-10 22:19
What about something like:

`<podcast:season title=“2020 Election”>2</podcast:season>`

Would that fit your use case?

It keeps the numbering so that it’s easy for aggregators to handle/sort by, but allows for a string title.

**Comment by staceygoers** [comment] 2020-11-10 23:06
hmm it could. We're also aching to free up space for specific titles, so yeah, this helps!

**Comment by theDanielJLewis** [comment] 2020-11-11 01:57
I like the attribute approach. I think that makes it easy to support.

**Comment by daveajones** [comment] 2020-11-11 15:01
Ok I’ll write this up today.

**Comment by saerdnaer** [comment] 2020-11-11 16:39
You could also sink about generic groupings e.g. to group multi part series in collection feeds – compare "Stahnke" in https://www.ardaudiothek.de/hoerspiel-pool/7263856/alle  

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/40266/98838556-b819b280-2444-11eb-88ba-59ae32e3888b.png">

**Comment by daveajones** [comment] 2020-11-11 16:57
Interesting. I worry about that being _too_ generic though, unless there is some sort of intent directive.

**Comment by daveajones** [comment] 2020-11-11 21:19
Ok, written up.  I'll link to it on podcastindex.social to see if anyone has further comment.

**Comment by coldacid** [comment] 2020-11-13 01:53
@daveajones @staceygoers do we want to make this just about seasons? I'd still like to see non-integer episode number support, although my old proposal #101 would have to be revised to bring it in line with this proposal.

**Comment by theDanielJLewis** [comment] 2020-11-13 01:57
I think we could let the tag be self-closing to make it use the label/title _instead of_ a season number.

For example:

`<podcast:season title="beginner">1</podcast:season>`

Could then be displayed as "Season 1: Beginner."

Change it to:

`<podcast:season title="beginner" />`

And it would then be displayed as "Beginner."

**Comment by coldacid** [comment] 2020-11-13 01:59
How about sorting in that situation though?

**Comment by theDanielJLewis** [comment] 2020-11-13 02:04
Good point. The number might be necessary to keep then, if for no other reason but for sorting, and then rely completely on the `title` attribute for the text instead of automatically adding the season number to it.

Or maybe like Apple Podcasts has the episode number and episode title tags separated, we could make `<podcast:seasonTitle>`.

**Comment by mitchdowney** [comment] 2020-11-13 03:24
What do you think about adding more info like this?

```
<podcast:season title="The Beginning" episodeCount="10">1</podcast:season>
<podcast:episode title="Pilot" season="1">1</podcast:episode>
```

Everything would be optional except the nodes.

And I don't know how crazy we want to get here but what about content that belongs to a season, might be serialized, but is not an episode? Should we allow a float or some other non-integer for the episode number, so content can be ordered between episodes?

```
<podcast:episode title="Pilot" season="1">1</podcast:episode>
<podcast:episode title="Behind the Scenes: Pilot" season="1">1.1</podcast:episode>
<podcast:episode title="Episode 2" season="1">2</podcast:episode>
<podcast:episode title="Behind the Scenes: Episode 2" season="1">2.1</podcast:episode>
<podcast:episode title="Episode 2 Outtakes" season="1">2.2</podcast:episode>
```

**Comment by daveajones** [comment] 2020-11-13 03:53
I like where this is headed.

**Comment by coldacid** [comment] 2020-11-13 13:36
I don't think we should include episode title, since that duplicates the existing item title. Other than that, @mitchdowney you've essentially copied #101. Given the goals stated in README.md, we should go with separate season and episode tags, with the tagged content being the actual season or episode number (allowing for decimal numbers) and an attribute for a human-friendly rendition of the number if it shouldn't be displayed "raw".

Example:

```xml
<title>March 2020: Outtakes</title>
<podcast:season title="2020">2</podcast:season>
<podcast:episode display="Special 1">3.1</podcast:episode>
```

The season would be shown as "2020" while sorted as the second season. This episode would be sorted after the third episode of the second season, with the episode number displayed as "Special 1".

**Comment by mitchdowney** [comment] 2020-11-13 14:58
Very cool. Display attribute makes a lot of sense to me. Couple thoughts...

- Are we sure <podcast:season> shouldn’t be set at channel level? Main reason I thought of putting it there was to avoid needing to repeat season title in every item’s <podcast:season> tag. Each episode could inherit from the channel tag.

- Also sorry I’m new to this process, but after reading the README and Winer’s post, why is something like <podcast:episode season=“1”>1</> definitely a no go? I was thinking this would be more efficient than a separate <podcast:season> and <podcast:episode> tag in each item since we could set <podcast:season title> at channel level, then just set the <podcast:episode season> tag at the item level, with season optional. It seems more reliable to me if season title is declared in one place so it can be inherited by episodes, to prevent mismatched season data in items. If you could help me understand what principle/s this clashes with I’d appreciate it.

**Comment by coldacid** [comment] 2020-11-13 16:24
To your first point, an RSS feed might contain the latest X episodes or it might contain all episodes for a show. In either case, there could be episodes from two or more different seasons in it. If the season tag is at channel instead of item level, then we can't do this. If it's allowed at either channel or item level, then we need to determine what happens when the tag appears at both levels. The KISS principle says just stick it at item level and we don't need to worry about all of that.

For your second point, the Apple Podcasts RSS spec already offers episode number and season number tags at the item level, which take as the tag content an integer value for each. Since we explicitly want non-integer episode (and maybe season) numbers, goal 1 doesn't apply, but goal 3 still does, which says we should stick to existing conventions. Following that goal means we essentially duplicate the existing schema of those Apple tags, but change the content type from integer to decimal, and then add optional attributes for the further extension of providing titles or other display values (per goal 2). Efficiency is nice, but it is not as important as the specified goals when working out this schema.

**Comment by mitchdowney** [comment] 2020-11-13 19:03
This helps me a ton @coldacid thanks for the explanation.

**Comment by theDanielJLewis** [comment] 2020-12-05 16:03
I thought of something potentially related to this.

What if we look at "named" seasons more like tags or categories? This would support putting an episode in multiple groupings.

For example, a movie review podcast might have categories for sci-fi, action, drama, kids, etc. And one of the movies they cover is a sci-fi drama, so it would be worth putting in both categories.

This _might_ even be worth adding internal categorization instead of non-integer seasons, because this would be more flexible. (Though I do still think seasons should have optional names.)

**Comment by daveajones** [comment] 2020-12-05 20:38
This is a neat idea. Would this be more appropriate for the “episode” tag?

**Comment by coldacid** [comment] 2020-12-05 22:20
I think treating named seasons as tags or categories is completely outside the scope of the ask here. For categories, there's already both itunes:category *and* podcast:category. For tags, we could certainly kick itunes:keywords to the curb with a new tag that doesn't treat things as a dumb comma-separated list, but that's again outside the scope of this issue. I don't think either of these things would be appropriate for the episode tag, either.

**Comment by coldacid** [comment] 2020-12-05 22:39
@theDanielJLewis @daveajones per my last comment, please see #137. I think that'd be a lot more useful for bucketing/grouping episodes or possibly even entire shows.

**Comment by daveajones** [comment] 2020-12-16 23:56
This is a simple change/tag.  But, I'm still trying to figure out how this relates (_could_ relate) to an episode tag.  I just can't see one without the other.

**Comment by theDanielJLewis** [comment] 2020-12-18 19:01
> And I don't know how crazy we want to get here but what about content that belongs to a season, might be serialized, but is not an episode? Should we allow a float or some other non-integer for the episode number, so content can be ordered between episodes?

I don't think that will be necessary. As it is right now, I think all the apps still _sort_ by `pubDate`, even though they _group_ by season (if present).

> This is a simple change/tag. But, I'm still trying to figure out how this relates (_could_ relate) to an episode tag. I just can't see one without the other. Seems like they both need to be there. But, referencing an itunes namespace tag from another namespace seems gross and broken.

The iTunes namespace does allow for seasons and episode numbers to be used together or independently, and there are good use cases for this. Think simply of someone who doesn't care about episode numbers (they really aren't as important as a lot of people make them), but _does_ want their content grouped into seasons (whether by schedule or by theme).

I often challenge podcasters to consider avoiding episode numbers if they can. I think it's one of those things that we do simply because we see others do it.

**Comment by daveajones** [comment] 2020-12-18 20:43
> I often challenge podcasters to consider avoiding episode numbers if they can. I think it's one of those things that we do simply because we see others do it.

Interesting.

@staceygoers Do you guys have a standard to use <itunes:episode> in all of your feeds, or do you just use <itunes:season>?

**Comment by staceygoers** [comment] 2020-12-18 20:59
I've let the wise minds battle this one out. :) This has been a fun convo to watch!

We use both, but not **required**. Up First, for example, shouldn't use either.

If we use season, we nearly **always** use episode. 
However, we do use episode alone, without seasons (think Planet Money).

Again, it would be amazing if, for example, Embedded could add a tag to their Mitch McConnell season -- see how we use the headline naming to get around it a bit here. https://www.npr.org/podcasts/510311/embedded

**Comment by daveajones** [comment] 2020-12-18 21:49
> If we use season, we nearly **always** use episode.

Hmm.  I think that makes sense, even if it's purely a psychological thing.  When listeners see a show grouped into "seasons", it feels good to see the episode number listed for each episode to make sure you aren't missing any of them.  

> Think simply of someone who doesn't care about episode numbers (they really aren't as important as a lot of people make them)

I agree.  Outside of a season context, the episode numberings aren't very meaningful, except for the psychological part (for the podcaster and the listener both).  It probably feels good to see that new number pop up.  It's a sort of signal of how far you've come (again, on both sides).

Thinking out loud here... Having the episode number as a standalone tag allows for numbering to be taken out of the `<title>`, which is always a cleaner structure.  It allows an app to display the number in the UI in a more flexible way.  I could even see a toggle box to allow showing/hiding them beside the titles.  The episode number isn't part of a title.  For example, ["Land & Power"](https://www.npr.org/podcasts/935323333/land-power) episode 4's title is "Reclaim, Remain, Rebuild Our Cities".  It's title is not "Ep. 4: 'Reclaim, Remain, Rebuild Our Cities'".

Mulling...

**Comment by theDanielJLewis** [comment] 2020-12-18 21:58
> Thinking out loud here... Having the episode number as a standalone tag allows for numbering to be taken out of the <title>, which is always a cleaner structure. It allows an app to display the number in the UI in a more flexible way. I could even see a toggle box to allow showing/hiding them beside the titles. The episode number isn't part of a title. For example, "Land & Power" episode 4's title is "Reclaim, Remain, Rebuild Our Cities". It's title is not "Ep. 4: 'Reclaim, Remain, Rebuild Our Cities'".

That's the way the iTunes namespace works with Apple Podcasts. There's the `<title>` tag that can contain season and episode, but the `<itunes:title>` should contain _only_ the episode title, while `<itunes:episode>` and `<itunes:season>` contain episode and season numbers, respectively.

So we might want to have a `<podcast:title>` item-level tag to offer a similar clean title and the podcast apps will fall back to `<title>` if they don't support the cleaner titles. This is how Apple Podcasts works.

The iTunes season or episode numbers will be ignored in Apple Podcasts if the iTunes title is absent.

**Comment by daveajones** [comment] 2020-12-18 23:06
> The iTunes season or episode numbers will be ignored in Apple Podcasts if the iTunes title is absent.

Really?  Now, that's interesting.  Just within the Apple Podcasts app, or also in the apple web listings?

**Comment by theDanielJLewis** [comment] 2020-12-18 23:16
Both places.

I recently experimented with removing episode numbers from my episode `<title>` tags and populating only the `<itunes:episode>` tag, but AP wouldn't display the episode number because there was no `<itunes:title>`. I reached out to Apple and to Angelo Mandato (Blubrry/PowerPress developer) and both confirmed that `<itunes:title>` must be present for the episode number. But I didn't ask or test for the season number.

**Comment by daveajones** [comment] 2020-12-18 23:18
Thanks for that info.

**Comment by saerdnaer** [comment] 2021-01-20 19:16
I am not sure how I should read the current spec:
Is `<podcast:season name="Race for the White House 2020"/>` a valid element, or is the season integer required?

**Comment by daveajones** [comment] 2021-01-21 13:11
The integer in the node value is required for two reasons:

- keeps apps from having to change logic if they are just adding support for this tag in addition to itunes:season
- allows for sorting by season in a way that the creator wants them to be organized. I can’t think of any other way to do that than have the number present

I’ll check the wording of the tag write up and clarify.  If I’m missing an obvious problem with this reasoning let me know.

**Comment by staceygoers** [comment] 2021-01-21 15:05
+1 to Dave's comments. Less required moving for apps, allow for the sorting.

**Comment by coldacid** [comment] 2021-01-21 16:45
Sounds good to me. @daveajones you probably just have to state that the season number in the tag's value is required and not make any other changes to the text for it.

@saerdnaer I hope this clears it up for you!

**Comment by saerdnaer** [comment] 2021-01-21 19:51
Should we specify an additonal tag on the channel level, specifying it the season number should/n't be displayed by a client or should the rss feed authors always include the  season number in the name if they want it to be shown additonally?

**Comment by daveajones** [comment] 2021-01-22 03:47
@saerdnaer Hmm. My inclination is to leave it up to the apps, but then again it’s a sort of creative decision too.  I think I’ll post this to the developers on podcastindex.social and get their feedback on UI considerations.

**Comment by saerdnaer** [comment] 2021-01-25 15:39
It depends on the kind of podcast. If you have only 2-6 seasons (e.g. TAL Serial) displaying the number would work, if you have a collection podcast with multiple audiobooks episodes from different publishers, each book as one season nobody cares about  the internal season number of that podcast, only the title of the book to group the chapters of that book together.

**Comment by daveajones** [comment] 2021-01-26 04:35
True. But, requiring the season number doesn’t hurt you really at that point. They can be ignored by the app. 

It also doesn’t say that the season numbers must be unique. So, technically you could just put every season number as a 0 to note that ordering is unnecessary.  If that wording was present would that make things read better to you?

**Comment by coldacid** [comment] 2021-01-26 15:33
I'm not sure if giving season number as 0 for differently named seasons will work based on the current spec wording. Considering that season and episode numbers work hand-in-hand, you'd end up with incorrect episode sorting. Taking the audiobook scenario, you'd have all the first episodes for each book, followed by the second episodes for each book, etc. Therefore, there would need to be a different season number for each book.

Also, while there's nothing saying that season numbers must be unique, it is certainly implied that there would be only one name for a particular season number given prior art in other media. With that in mind maybe we should have a new boolean attribute on the season tag that says whether or not to display the season number.

**Comment by daveajones** [comment] 2021-02-04 15:04
I think this wording captures the spirit of things about as good as we can get:

https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#season

Unless someone has an amazing argument at this point, I'm considering this one to be fully formalized.

**Comment by theDanielJLewis** [comment] 2021-02-04 15:19
I think it looks good.

(I'm sorry that I've missed most of the latest conversation on this, but I think the end result is good.)

**Comment by staceygoers** [comment] 2021-02-04 15:20
Agreed! Thank you!

**Closed** 2021-02-04 16:05 UTC
